package android.example.com.aakashmodel;

import androidx.appcompat.app.AppCompatActivity;

import android.content.Intent;
import android.os.Bundle;
import android.util.Log;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.TextView;
import android.widget.Toast;

import org.w3c.dom.Text;

public class AddActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_add);

        //submit button in AddActivity layout resource file for form submission of report card
        Button reportCardSubmit = (Button) findViewById(R.id.submit_report_card);
        reportCardSubmit.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                addReportCard();
            }
        });
    }

    public void addReportCard() {
        //Create instance of all EditText to get user input using getText method of EditText class for object by
        //casting of returned object from findViewById(id of view in layout resource file in our case EditText)
        EditText nameText = (EditText) findViewById(R.id.nameEditText);
        String name = nameText.getText().toString();

        EditText cPlusPlusText = (EditText) findViewById(R.id.cPlusPlusEditText);
        String cPlusPlus = cPlusPlusText.getText().toString();

        EditText pythonText = (EditText) findViewById(R.id.pythonEditText);
        String python = pythonText.getText().toString();

        EditText javaText = (EditText) findViewById(R.id.javaEditText);
        String java = javaText.getText().toString();

        if(name.length() >= 1 && cPlusPlus.length() >= 1 && python.length() >= 1 && java.length() >= 1) {
            //method add the data object for report card of student in Database static ArrayList of ReportCard(have variable and method for view
            // item of Recycler View List ) class type
            Database.addReportCard(name, cPlusPlus,python,java);
            //Display popup message for 1sec duration.
            Toast.makeText(getApplicationContext(), "Report Card Saved Successfully", Toast.LENGTH_LONG).show();
            //Explicit intent to open Activity component of Application MainActivity.class(byte code file for Encryption generated by JRE(Java Runtime Environment development tools of JDK)
            Intent intentForMainActivity = new Intent(getApplicationContext(), MainActivity.class);
            startActivity(intentForMainActivity);
        } else {
            //TextView object by casting(same type of variable where assign object in parentheses) return object from findViewById(id of view) (method of AppCompatActivity of androidx.appcompat.app package for app compatability on every version of android almost and method find View from
            //view hierarchy of layout resource file of android app by view id and return that view as object of View class because every widget class parent is View.
            TextView problemDialogTextView = (TextView) findViewById(R.id.problem_dialog_add);//Display error in form submission of adding report card
            problemDialogTextView.setText("*Problem: One or More Fields are Blank");
            problemDialogTextView.setVisibility(View.VISIBLE);
            Toast.makeText(getApplicationContext(), "Fill All Details First", Toast.LENGTH_LONG).show();
        }
    }
}